### ISSUE TITLE
Melhorias na Introdução

### ISSUE THREAD

**Issue by danielasy** [hedwig-project/monografia#30]
- Trazer mais fontes pra parte de motivação
- Revisar seção de Machine Learning

**Comment by vthayashi** [comment]
https://www.i-scoop.eu/smart-home-home-automation/iot-home-automation-applications/

**Comment by danielasy** [comment]
https://hbr.org/2014/07/how-the-internet-of-things-changes-business-models
https://hbr.org/2014/11/how-smart-connected-products-are-transforming-competition

**Comment by danielasy** [comment]
https://www.cisco.com/c/en/us/solutions/collateral/service-provider/visual-networking-index-vni/vni-hyperconnectivity-wp.pdf
