### ISSUE TITLE
Dividir texto dos módulos locais entre as seções de arquitetura e implementação

### ISSUE THREAD

**Issue by gabimelo** [hedwig-project/monografia#46]
Acho que da pra colocar também as infos do [arquivo de montagem dos módulos, no drive](https://docs.google.com/document/d/1D4_4m9D8gpRFzF6kYvbH7q2r9V4M8AR3RKsSHuhNSMg/edit#), na seção de implementação

**Comment by vthayashi** [comment]
lembrar de separar conforme o servidor local, deixar ESP (tecnologia usada) na arquitetura e o restante na implementação

**Comment by vthayashi** [comment]
escrever também sobre implementação do protocolo em MQTT pelo lado do módulo

**Comment by vthayashi** [comment]
Descrições completas dos módulos
