### ISSUE TITLE
Ajuste seçao `/Arquitetura/Comunicação` (vide descrição)

### ISSUE THREAD

**Issue by gabimelo** [hedwig-project/monografia#48]
O texto está descrevendo especificamente a comunicacao entre módulos e controlador local, e levemente sobre a comunicação entre controlador local e nuvem. É necessário falar da comunicação entre as outras partes do sistema também (vide subseções que estavam previstas), e ver se vamos dividir nas subseções ou matá-las

**Comment by vthayashi** [comment]
acho que poderíamos falar um pouco sobre a comunicação das outras partes sim, e passar essa parte que está no "Morpheus" para as subseções que a gente tinha pensado

**Comment by vthayashi** [comment]
deixei comentado por enqto. As comunicações estão na seção do Morpheus.

**Comment by danielasy** [comment]
Vejam se #81 está bom ou precisamos por mais algo lá

**Comment by gabimelo** [comment]
@danielasy @vthayashi acham que precisaria também de uma seção de comunicacao nuvem-dashboard ou é meio óbvio?

**Comment by danielasy** [comment]
@gabimelo @vthayashi adicionei essa parte em #87

**Comment by vthayashi** [comment]
@danielasy adicionei a parte de comunicação módulos - app tbm
