### ISSUE TITLE
Fazer diagrama de sequência geral do sistema

### ISSUE THREAD

**Issue by gabimelo** [hedwig-project/monografia#65]

**Comment by vthayashi** [comment]
https://drive.google.com/open?id=1hEz5Krmu6CynPjhx1jzr23NAlMbOU11B
https://drive.google.com/file/d/12gJ_JxyGAYU-cV9XmomxJWOeJ0P_tQK6/view?usp=sharing
https://drive.google.com/file/d/1Fj5hE-cNeYpx4E0MFbwQmPAbLqzUoi8v/view?usp=sharing
https://drive.google.com/file/d/19FaLz-W_79SpVSriB6YnBEWcqQDFk2_F/view?usp=sharing

Nas explicações (texto corrido na monografia mesmo) eu colocaria o tempo de resposta (sequencia_action_config) e entre atualizações de dados (sequencia_data) que obtivemos.

Não sei se a gente inclui tbm o role do usuário não poder clicar várias vezes e ficar piscando a luz (não sei se é uma dúvida que podem ter)

Comentar tbm sobre RF e botão físico (user direto com módulo)
