### ISSUE TITLE
Capítulo de Metodologia

### ISSUE THREAD

**Issue by danielasy** [hedwig-project/monografia#80]
- [x] Gerência de processos de software: mencionar nossos ciclos de desenvolvimento e testes?
- [x] Gerência de aquisição: pelo menos mencionar que a lista de materiais está nos anexos e dizer que os componentes são baratos e acessíveis?
- [x] Pesquisa bibliográfica: dar uma enchida talvez? constante utilização de documentação online de bibliotecas e ferramentas utilizadas, além de alguns livros consultados (ISLR foi altamente utilizado pra aprendizado de máquina por exemplo)
- [x] Ferramentas e tecnologias: dar mais uma enchida talvez?

Feedback Arakaki

- [x] Falar do método de provas de conceitos como elemento de técnicas ágeis;
- [x] Falar das discussões em grupo e plataformas de colaboração;
- [x] Falar das estratégias de testes adotadas;
-  Falar de uso de maquetes e implementações iniciais como especificação de implementações definitivas;
- [x] Comentar que a gestão de riscos incluiu as reuniões de vocês e com os orientadores periodicamente.

**Comment by danielasy** [comment]
Feedback Arakaki

- [ ] Falar do método de provas de conceitos como elemento de técnicas ágeis;
- [ ] Falar das discussões em grupo e plataformas de colaboração;
- [ ] Falar das estratégias de testes adotadas;
- [ ] Falar de uso de maquetes e implementações iniciais como especificação de implementações definitivas;
- [ ] Comentar que a gestão de riscos incluiu as reuniões de vocês e com os orientadores periodicamente.

**Comment by vthayashi** [comment]
Gerência de tempo: incluir cronograma como anexo?

**Comment by gabimelo** [comment]
@vthayashi seria aquele cronograma da lucia? Nao sei se compensa, acho q ele ta desatualizado e era meio grande de ler, ficava meio ruim

**Comment by gabimelo** [comment]
Eu acho na verdade que não precisaria da seção pesquisa bibliográfica. Acho que ela é explicitada pela presença das bibliografias ao longo do texto.

Se acharem válido manter, podemos falar da constante utilização de documentação online de bibliotecas e ferramentas utilizadas, além de alguns livros consultados (ISLR foi altamente utilizado pra aprendizado de máquina por exemplo)

Aliás, acho o mesmo para a seção Ferramentas e tecnologias também

**Comment by gabimelo** [comment]
Outra coisa, acham que precisa de Gerência de Partes Interessadas e Gerência de Escopo?

**Comment by vthayashi** [comment]
- Sobre o cronograma, como tava desatualizado mesmo, pode deixar quieto
- Mas acho válido deixar as seções pesquisa bibliográfica, citando ISLR e constante utilização de documentação online de bibliotecas como disse (incluindo tipo IDE q eu usei e bibliotecas para os módulos). Sempre acho a seção toda de Metodologia meio encheção...
- Eu incluiria a Gerência de Escopo e deixaria de fora a Gerência de Partes Interessadas

**Comment by gabimelo** [comment]
Finalizado em https://github.com/hedwig-project/monografia/pull/111
