### ISSUE TITLE
Adaptar título dos capítulos

### ISSUE THREAD

**Issue by gabimelo** [hedwig-project/monografia#83]
Como sugerido pelo Arakaki no email

**Comment by vthayashi** [comment]
Cap 3 - Trocar “ Especificação “  - Trocar por: “ Arquitetura: Especificação de negócios e de requisitos” 

Cap 4 - Complementar “ Arquitetura: Solução Técnica - Mecanismos ” 

Cap 5 - OK

Cap 6 - Arquitetura: Tecnologia e Implementação

Cap 7 - Arquitetura: Tecnologia - Aprendizado de máquinas e analise dos dados
