### ISSUE TITLE
Conclusões

### ISSUE THREAD

**Issue by gabimelo** [hedwig-project/monografia#9]

**Comment by vthayashi** [comment]
https://docs.google.com/document/d/1k_zNIc6O1YJS884aQZtZvyWKLbWLwuICJArEuwdfYCs/edit?usp=sharing

**Comment by hpossn** [comment]
https://docs.google.com/document/d/1LGQjkToeacJeRRedXDiCrY9yrkwBuK8Mn8H5NRk_mGY/edit
